### ISSUE TITLE
Critical bug!

### ISSUE THREAD

**Issue by LLjo** [someaddons/cursery#1]
**Describe the bug**
Holding down shift (crouch button) will make items not get any curses

**To Reproduce**
1. Put your item in the anvil and enchant it but always hold down shift and you will never get a curse

** Mod version **
2.2-1

**Comment by someaddons** [comment]
fixed in the newest^^ nice find

**Comment by LLjo** [comment]
Thanks, now I can feel more calm. Don't think anyone on the server discovered it :-)

**Comment by someaddons** [comment]
:D yea its quite the weird one, due to vanilla inventory slots functioning different for shift click than normal click
