### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by TheNimbleNinja** [someaddons/cursery#12]
### Describe the bug you're experiencing

crash on startup
version cursery-1.19.2-3.0.jar

### Reproducability

i added it to a massive modpack

### Mod up to date

- [X] Before submitting this issue I updated to the newest version and reproduced it

### Minecraft version

1.19

### Modloader version

Forge

### Logs

https://gist.github.com/TheNimbleNinja/72f967a1a9d940667f9cdf43405dc84d

**Comment by someaddons** [comment]
Your logs shows an incompat between apotheosis and uniquebase mod, how is it related to cursery?
