### ISSUE TITLE
Disabling curse chance

### ISSUE THREAD

**Issue by Naughty-Nitrax** [someaddons/cursery#2]
Not really much of an issue, just a personal request:
Currently I'm using this mod alongside the 'Enigmatic Legacy' mod; this mod has an item that gives a boost based on the amount of curses in your equipment. I wanted to add more curses for the potential boost, but would like to keep the treasure status so they aren't easy to come by either, however there's no such option in the mod's config file, would like an option/guide for disabling the cursing chance.

**Comment by someaddons** [comment]
you can adjust the chance for curses, but I won't add a config to disable 90% of what the mod's design is about

**Comment by Naughty-Nitrax** [comment]
Already lowered the chance to the minimum, but it's understandable if you don't wanna add that option.
