### ISSUE TITLE
Curses are easily avoided with Quark's Matrix Enchanter

### ISSUE THREAD

**Issue by kaylee-kiako** [someaddons/cursery#5]
### Versions
- Minecraft 1.18.2
- Forge 40.0.46
- AutoRegLib 1.7-53
- Cursery 1.18-2.9
- Quark 3.2-349
- Quark Oddities 1.18

### Issue

1. When using the Matrix Enchanter, a preview is displayed showing any enchantments and curses. 
2. Whenever a player places, moves, or removes a puzzle component, the item is regenerated, along with its chance of being cursed.
3. If a player previews the item and sees a curse, they may shift pieces around until they obtain an item that isn't cursed.

**Comment by MaliciousZoroark** [comment]
This also applies to Spectrum's Enchanter structure

**Comment by someaddons** [comment]
fixed in newest version
