### ISSUE TITLE
[Bug]: Is this bug?

### ISSUE THREAD

**Issue by SembleGit** [someaddons/cursery#6]
### Describe the bug you're experiencing

Bug in config file

### Reproducability

Step 1 : I followed the instructions to configure this mod, but I got an error.

"excludedCurses": [\"cursery:curse_illusion\", \"cursery:curse_electrified\", \"cursery:curse_switchy\", \"cursery:curse_explosive\", \"cursery:curse_undead\", \"cursery:curse_anvil\", \"cursery:curse_blindness\", \"cursery:curse_poison;\"]

this is so weird.
"desc:": "Add a curse id here to exclude it from beeing applied. To put multiple values seperate them by commas like this:  [\"minecraft:curse\", \"mod:curse;\"] "
You wrote this and I tried it as is but minecraft crashed

### Mod up to date

- [X] Before submitting this issue I updated to the newest version and reproduced it

### Minecraft version

1.19

### Modloader version

Fabric

### Logs

https://gist.github.com/SembleGit/a9abb412a5e731e723fc45547213fe6a

**Comment by someaddons** [comment]
should be fine, your crash looks odd, for some reason sodium is crashing? Cursery lets you start even with a broken config
