### ISSUE TITLE
[Mod Conflict Bug] Conflict with Mod Simple Diving Gears

### ISSUE THREAD

**Issue by JuicyCosmos** [someaddons/cursery#7]
### Describe the bug you're experiencing

Basically some diving gears from Simple Diving Gears work by auto-enchanting itself with Aqua Affinity and Depths Striders and such. 
When paired with Cursery those diving gears will build up curses at an ridiculous rate, even setting the chance to 1 will not prevent those gears from getting 10+ curses when equipped for a minute, effectively making the equipment unusable. With Cursery removed the bug no longer persists.
I suggest adding a blacklist in the config file for equipments and tools that should be prevented from getting cursed.

### Reproducability

Just install both Cursery and Simple Diving Gears. Equip, for example, the flippers or the diving tank and voilà, you now have a curse generator.

### Mod up to date

- [X] Before submitting this issue I updated to the newest version and reproduced it

### Minecraft version

1.19

### Modloader version

Forge

### Logs

No log required, just compat issue.

**Comment by someaddons** [comment]
not a bug, its as intended adding a curse on enchanting, should probably report to the gear mod, I see no reason why one would continuously re-enchant items over and over
