### ISSUE TITLE
[Bug]: Curses are added to equipment even through the /enchant command

### ISSUE THREAD

**Issue by Typhonidite** [someaddons/cursery#9]
### Describe the bug you're experiencing

When using the /enchant command to apply an enchantment to an equipment item (weapons, tools, armor...), curses are still added as if it was enchanted using an enchantment table or anvil.

### Reproducability

Use the /enchant command to enchant and piece of equipment. It may take a few tries.

### Mod up to date

- [X] Before submitting this issue I updated to the newest version and reproduced it

### Minecraft version

1.19

### Modloader version

Forge

### Logs

https://gist.github.com/Typhonidite/dca7181f0f828f102a90c5af3fafd29d

**Comment by someaddons** [comment]
Curse application has no context for the application to different between methods, so its not possible to just exclude commands. If you want to get pre-defined items without I'd advise loading them with enchanted nbt directly
